name: Deploy to x Server

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github actions repository
        uses: actions/checkout@v2

      - name: set up SSH connection and copy files
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: ${{ github.workspace }}/ssh-auth.sock

      - name: Copy files to remote server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }}" . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
